---
title: "My R Template"
author: "[Haotian Zheng](https://github.com/marveloushaotian)"
date: "`r Sys.Date()`"
output: html_document
---
**This document analysis:**  
*1.*  
*2.*  

***

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE) # Need to change the path of the plot.

library(knitr) # evaluate the code, putting the results in a markdown document, which can then be converted to a variety of formats with pandoc.
library(tidyverse) # including ggplot2,dplyr,tidyr,readr,purrr,tibble,stringr,forcats.
# Matrix processing
library(reshape2) # 'melt', 'cast' rebuild database.
library(plyr)
library(data.table)

# Statistic.
library(scales) # generic function whose default method centers and/or scales the columns of a numeric matrix.
library(psych)
library(vegan)
library(randomForest)
library(caret)

# Visualization.
library(igraph)
library(ggrepel) # repel overlapping text labels.
library(ggthemes) # contains extra themes, scales, and geoms, and functions for and related to ggplot2.
library(ggpubr) # facilitates the creation of beautiful ggplot2-based graphs.
library(gg.gap) # Easy to define segments in y-axis for 'ggplot2'.
library(ggbreak) # Effectively Utilize Plotting Space to Deal With Large Datasets and Outliers.
library(RColorBrewer)
library(pheatmap) # A function to draw clustered heatmaps.
library(gggenes) # provides a 'ggplot2' geom and helper functions for draw- ing gene arrow maps.
library(gggenomes)

do.write <- F
options(scipen = 200)
```

#### Import data.
```{r}

```

***

#### Filter data.
```{r}

```

***

#### Visualization.
```{r}
ggplot(plot_data,aes(x=var1,y=var2)) + 
  # geom_bar(fill="steelblue",stat = 'identity',width = 0.8) +
  geom_text(aes(label=var1),vjust = -0.2, hjust = 0.5,position = position_dodge2(width = 0.1, preserve = 'single')) + 
  # scale_x_continuous(breaks = c(0:13)) + 
  # scale_y_break(c(2050,29500),ticklabels = c(29500,30000),scales = 0.1) +
  labs(x="Size group", y="ratio(system number/plasmids number)") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 20, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.x = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.y = element_text(size = 15, face = "bold", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.x = element_text(size = 10, face = "plain", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.y = element_text(size = 10, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        legend.title = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.text = element_text(size = 12, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.key = element_rect(fill = 'transparent'),
        legend.position = 'bottom',
        legend.key.size=unit(0.8,'cm'),
        legend.key.width=unit(1.2,'cm'),
        legend.spacing.y = unit(0.5,"cm"),
        # plot.margin = unit(c(1, 1, 1, 1),'cm'),
        strip.text.y = element_text(size=15,face = "bold"),
        strip.text.x = element_text(size=15,face = "bold")
        )
```

***

##### Fin.