---
title: "System number - environemnt site"
author: "[Haotian Zheng](https://github.com/marveloushaotian)"
date: "`r Sys.Date()`"
output: html_document
---
**This document analysis:**  
*1.Make a plasmid env categoty, and choose jakobs way to sort it.*  
*2.*  

***

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE) # Need to change the path of the plot.

library(knitr) # evaluate the code, putting the results in a markdown document, which can then be converted to a variety of formats with pandoc.
library(tidyverse) # including ggplot2,dplyr,tidyr,readr,purrr,tibble,stringr,forcats.
# Matrix processing
library(reshape2) # 'melt', 'cast' rebuild database.
library(plyr)
library(data.table)

# Statistic.
library(scales) # generic function whose default method centers and/or scales the columns of a numeric matrix.
library(psych)
library(vegan)
library(randomForest)
library(caret)

# Visualization.
library(igraph)
library(ggrepel) # repel overlapping text labels.
library(ggthemes) # contains extra themes, scales, and geoms, and functions for and related to ggplot2.
library(ggpubr) # facilitates the creation of beautiful ggplot2-based graphs.
library(gg.gap) # Easy to define segments in y-axis for 'ggplot2'.
library(ggbreak) # Effectively Utilize Plotting Space to Deal With Large Datasets and Outliers.
library(RColorBrewer)
library(pheatmap) # A function to draw clustered heatmaps.
library(gggenes) # provides a 'ggplot2' geom and helper functions for draw- ing gene arrow maps.
library(gggenomes)

do.write <- F
options(scipen = 200)
```

#### Import data.
```{r}
metadata_origin <- read_tsv("../../Results/00.Original_Data/00.meta_data/plsdb_filtered.tsv")

metadata <- read.delim("../../Results/00.Original_Data/00.meta_data/plsdb_metadata_inuse.txt",header = T,check.names = F,sep = "\t")
combine_data <- read.table("../../Results/00.Original_Data/all_combined_data.txt",header = T,check.names = F,sep = "\t")
```

***

#### Filter data.
```{r}
metadata_iso_host <- metadata_origin %>% filter(metadata_origin$IsolationSource_BIOSAMPLE != "" | metadata_origin$Host_BIOSAMPLE != "")
metadata_iso_host$TAG <- paste(metadata_iso_host$IsolationSource_BIOSAMPLE,"_",metadata_iso_host$Host_BIOSAMPLE)
metadata_tag_order <- tapply(metadata_iso_host$TAG, metadata_iso_host$TAG, length) %>% as.data.frame() %>% rownames_to_column("TAG")
metadata_tag_order <- metadata_tag_order %>% dplyr::rename(Tag_count = ".")
metadata_tag_order2 <- metadata_tag_order %>% filter(metadata_tag_order$Tag_count > 9)
metadata_tag_order3 <- metadata_tag_order %>% filter(metadata_tag_order$Tag_count <= 9)

# metadata_pfamily <- metadata_origin %>% filter(metadata_origin$pmlst != "")
# metadata_pf <- str_split_fixed(metadata_pfamily$pmlst, " ", 2) %>% as.data.frame()
# metadata_pf_order <- tapply(metadata_pf$V1, metadata_pf$V1, length) %>% as.data.frame() %>% rownames_to_column("plasmidfinder")
# metadata_pf_order <- metadata_pf_order %>% dplyr::rename(Tag_count = ".")

library(mixtools)
f <- normalmixEM2comp(log10(metadata_tag_order$Tag_count), sigsqrd = c(1,2), mu = c(3,5), lambda = 0.5)
param <- 10^m$mu

ggplot(metadata_tag_order, aes(Tag_count)) +
    theme_bw() +
    geom_density() +
    # geom_vline(data = line_df, aes(xintercept = Length)) +
    # geom_text(data = line_df, aes(label = LengthS, y = Place, x = Length), hjust = -0.2, size = 3) +
    scale_x_log10(labels = COEF::fancy_scientific) +
    xlab("Count Number") +
    ylab("Density")




write.table(metadata_tag_order2, "../../Results/00.Original_Data/00.meta_data/plsdb_filtered_tag.txt", sep = "\t", row.names = F)
```

***

#### Visualization.
```{r}

```

***

##### Fin.