---
title: "Metadata Analysis"
author: "Haotian Zheng"
date: "24/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggrepel)
library(gggenes)
library(gg.gap)
library(ggbreak)
library(ggthemes)
library(ggpubr)
library(gtools)
library(igraph)
library(RColorBrewer)
library(dplyr)
library(plyr)
library(reshape2)
library(pheatmap)
library(readxl)
library(tibble)
library(scales)
library(psych)
library(vegan)
library(tidyverse)
library(knitr)
library(stringr)
library(ggalt)
do.write <- F
options(scipen = 200)
```

### import data.
```{r}
metadata_origin <- read_tsv("../../Results/00.Original_Data/00.meta_data/plsdb_filtered.tsv")

metadata <- read.delim("../../Results/00.Original_Data/00.meta_data/plsdb_metadata_mar.txt",header = T,check.names = F,sep = "\t")
combine_data <- read.table("../../Results/00.Original_Data/all_combined_data.txt",header = T,check.names = F,sep = "\t")
```

### filter data.
```{r}
metadata_iso_host <- metadata_origin %>% filter(metadata_origin$IsolationSource_BIOSAMPLE != "" | metadata_origin$Host_BIOSAMPLE != "")
metadata_iso_host$TAG <- paste(metadata_iso_host$IsolationSource_BIOSAMPLE,"_",metadata_iso_host$Host_BIOSAMPLE)
metadata_tag_order <- tapply(metadata_iso_host$TAG, metadata_iso_host$TAG, length) %>% as.data.frame() %>% rownames_to_column("TAG")
metadata_tag_order <- metadata_tag_order %>% dplyr::rename(Tag_count = ".")
metadata_tag_order2 <- metadata_tag_order %>% filter(metadata_tag_order$Tag_count > 9)
metadata_tag_order3 <- metadata_tag_order %>% filter(metadata_tag_order$Tag_count <= 9)

# metadata_pfamily <- metadata_origin %>% filter(metadata_origin$pmlst != "")
# metadata_pf <- str_split_fixed(metadata_pfamily$pmlst, " ", 2) %>% as.data.frame()
# metadata_pf_order <- tapply(metadata_pf$V1, metadata_pf$V1, length) %>% as.data.frame() %>% rownames_to_column("plasmidfinder")
# metadata_pf_order <- metadata_pf_order %>% dplyr::rename(Tag_count = ".")

library(mixtools)
f <- normalmixEM2comp(log10(metadata_tag_order$Tag_count), sigsqrd = c(1,2), mu = c(3,5), lambda = 0.5)
param <- 10^m$mu

ggplot(metadata_tag_order, aes(Tag_count)) +
    theme_bw() +
    geom_density() +
    # geom_vline(data = line_df, aes(xintercept = Length)) +
    # geom_text(data = line_df, aes(label = LengthS, y = Place, x = Length), hjust = -0.2, size = 3) +
    scale_x_log10(labels = COEF::fancy_scientific) +
    xlab("Count Number") +
    ylab("Density")




write.table(metadata_tag_order2, "../../Results/00.Original_Data/00.meta_data/plsdb_filtered_tag.txt", sep = "\t", row.names = F)
```


### pheatmap.
#### host-subtype.

#### host-subtype.



### Inc plot.
```{r}
metadata_origin <- read_tsv("../../Results/00.Original_Data/00.meta_data/plsdb_filtered.tsv")
combine_data <- read.table("../../Results/00.Original_Data/all_combined_data.txt",header = T,check.names = F,sep = "\t")
metadata_origin <- metadata_origin %>% dplyr::rename(Plasmid_ID=ACC_NUCCORE)
metadata_origin_sel <- metadata_origin[,c(1,11)]
combine_data_sel <- combine_data[,c(1,2)] %>% unique()
combine_inc <- left_join(metadata_origin_sel,combine_data_sel)
combine_inc <- combine_inc %>% dplyr::rename(Group=Defense_System_Type)
inc_plasmids2 <- combine_inc[grepl("Inc|Col", combine_inc$plasmidfinder), ]
inc_plasmids2[is.na(inc_plasmids2)] <- "None"
```

```{r}
inc_plasmids2$plasmidfinder <- gsub("ColRNAI_rep_cluster_[0-9]*", "ColRNAI", inc_plasmids2$plasmidfinder)

randomize <- function(x){
    df <- inc_plasmids
    df$CRISPRorCas <- sample(df$CRISPRorCas)
    res <- data.frame(table(unlist(lapply(as.character(df[df$CRISPRorCas, "Inc"]), function(x) strsplit(x, ",")))))
    return(res)
}

obs_inc <- data.frame(table(unlist(lapply(as.character(inc_plasmids[inc_plasmids$CRISPRorCas, "Inc"]),
                                         function(x) strsplit(x, ",")))))

set.seed(42)
rand_inc <- lapply(1:1000, randomize)

test <- Reduce(function(x, y) merge(x, y, by = "Var1", all = TRUE), rand_inc)
test[is.na(test)] <- 0

random_inc <- data.frame(Inc = test$Var1,
                         Freq = rowMeans(test[, -1]),
                         Freq.sd = apply(test[, -1], 1, sd))

combine_inc <- merge(obs_inc, random_inc, by.x = "Var1", by.y = "Inc", all = TRUE)
combine_inc <- combine_inc[!grepl("rep", combine_inc$Var1), ]
combine_inc[is.na(combine_inc$Freq.x), "Freq.x"] <- 0

combine_inc$Ratio <- combine_inc$Freq.x - combine_inc$Freq.y
combine_inc$Rand_max <- (combine_inc$Freq.y + combine_inc$Freq.sd)
combine_inc$Rand_min <- (combine_inc$Freq.y - combine_inc$Freq.sd)
combine_inc[combine_inc$Rand_min < 0, "Rand_min"] <- 0

combine_inc$Ratio_max <- combine_inc$Freq.x - combine_inc$Rand_min
combine_inc$Ratio_min <- combine_inc$Freq.x - combine_inc$Rand_max

combine_inc$Var1 <- as.character(combine_inc$Var1)

inc_prev <- data.frame(table(unlist(lapply(as.character(inc_plasmids$Inc), function(x) strsplit(x, ",")))))
inc_prev <- inc_prev[!grepl("rep", inc_prev$Var1), ]

combine_inc <- merge(combine_inc, inc_prev, by = "Var1")

combine_inc$IncN <- paste0(combine_inc$Var1, " (n=", combine_inc$Freq, ")")

p <- ggplot(combine_inc, aes(IncN, Ratio, ymin = Ratio_min, ymax = Ratio_max)) +
    theme_bw() +
    geom_point() +
    geom_errorbar() +
    coord_flip() +
    ylab("Difference (Observed - Random)") +
    xlab(NULL)
p
ggsave(p, file = "../Figures/Fig2_inc_all_supp.pdf", width = 16, height = 16, units = "cm")
write.csv(inc_plasmids[, c("Inc", "CRISPRorCas")], file = "../Tables/Fig2_Inc.csv", quote = FALSE, row.names = FALSE)
```

### normalize size plot. rate.
```{r}
combine_data <- read.table("../../Results/00.Original_Data/all_combined_data.txt",header = T,check.names = F,sep = "\t")
plsdb_ori <- read.delim2("../../Results/00.Original_Data/00.meta_data/plsdb_metadata_mar.txt", header = T, check.names = F, sep = "\t")

with_systems <- combine_data[,c(1,2,11)]
# with_systems$mintag <- floor(with_systems$Length/10000)*10
with_systems$maxtag <- ceiling(with_systems$Length/1000)
with_systems$mintag <- ceiling(with_systems$Length/1000) - 1#0
with_systems$tag <- paste0(with_systems$mintag,"-",with_systems$maxtag)

pre <- plsdb_ori %>% filter(plsdb_ori$Plasmid_ID %in% with_systems$Plasmid_ID)
without_systems <- setdiff(plsdb_ori,pre)[,c(1,3)]
without_systems$Defense_System_Type <- "None"
# without_systems$mintag <- floor(without_systems$Length/10000)*10
without_systems$maxtag <- ceiling(without_systems$Length/1000)
without_systems$mintag <- ceiling(without_systems$Length/1000) - 1#0
without_systems$tag <- paste0(without_systems$mintag,"-",without_systems$maxtag)


with_systems_number <- tapply(with_systems$tag, with_systems$tag, length) %>% as.data.frame() %>% rownames_to_column("tag")
with_systems_number <- with_systems_number %>% dplyr::rename(defense_number=".")

with_systems_plasmids <- with_systems[,c(1,6)] %>% unique()
with_systems_plasmids_number <- tapply(with_systems_plasmids$tag,with_systems_plasmids$tag,length) %>% as.data.frame() %>% rownames_to_column("tag")
with_systems_plasmids_number <- with_systems_plasmids_number %>% dplyr::rename(plasmid_number=".")


without_systems_number <- tapply(without_systems$tag, without_systems$tag, length) %>% as.data.frame() %>% rownames_to_column("tag")
without_systems_number <- without_systems_number %>% dplyr::rename(defense_number=".")
without_systems_number$defense_number <- 0

without_systems_plasmids <- without_systems[,c(1,6)] %>% unique()
without_systems_plasmids_number <- tapply(without_systems_plasmids$tag, without_systems_plasmids$tag, length) %>% as.data.frame() %>% rownames_to_column("tag")
without_systems_plasmids_number <- without_systems_plasmids_number %>% dplyr::rename(plasmid_number=".")

combine_system_number <- rbind(with_systems_number,without_systems_number)
combine_system_plasmids_number <- rbind(with_systems_plasmids_number,without_systems_plasmids_number)

combine_system_number2 <- aggregate(defense_number ~ tag, data = combine_system_number, sum)
combine_system_plasmids_number2 <- aggregate(plasmid_number ~ tag, data = combine_system_plasmids_number, sum)

combine_new <- cbind(combine_system_number2,combine_system_plasmids_number2)[,c(1,2,4)]

combine_new$ratio <- round(combine_new$defense_number/combine_new$plasmid_number,2)
combine_new$split <- str_split_fixed(combine_new$tag,"-",2)[,1]
combine_new$split <- as.numeric(combine_new$split)

combine_new2 <- combine_new[order(combine_new$split),]

combine_new2$split <- factor(combine_new2$split,levels = unique(combine_new2$split))
combine_new2$tag <- factor(combine_new2$tag,levels = unique(combine_new2$tag))

combine_new3 <- combine_new2 %>% filter(combine_new2$ratio != 0)
combine_new4 <- combine_new3 %>% filter(combine_new3$plasmid_number >= 10)

combine_new4$split <- as.numeric(combine_new4$split)
# combine_new4$tag <- as.character(combine_new4$tag)

ggplot(combine_new4,aes(x=split,y=ratio)) +
  # geom_bar(fill="steelblue",stat = 'identity',width = 0.8) +
  geom_point() + geom_smooth(method="loess",se=T) +
  geom_text(aes(label=ratio),vjust = -0.2, hjust = 0.5,position = position_dodge2(width = 0.1, preserve = 'single')) +
  # scale_x_continuous(breaks = c(0:13)) +
  # scale_y_break(c(2050,29500),ticklabels = c(29500,30000),scales = 0.1) +
  labs(x="Size group(Kb)", y="ratio(system number/plasmids number)") +
  theme_bw() +
  theme(plot.title = element_text(size = 20, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.x = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.y = element_text(size = 15, face = "bold", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.x = element_text(size = 10, face = "plain", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.text.y = element_text(size = 10, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        legend.title = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.text = element_text(size = 12, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.key = element_rect(fill = 'transparent'),
        legend.position = 'bottom',
        legend.key.size=unit(0.8,'cm'),
        legend.key.width=unit(1.2,'cm'),
        legend.spacing.y = unit(0.5,"cm"),
        # plot.margin = unit(c(1, 1, 1, 1),'cm'),
        strip.text.y = element_text(size=15,face = "bold"),
        strip.text.x = element_text(size=15,face = "bold")
        )
if(do.write){
  ggsave(width=12,height=8,filename="../../Results/01.Distribution/size_2.pdf",limitsize = FALSE)
}
```


```{r}
size_data <- read.table("../../Results/00.Original_Data/Size_group.txt",header = T,check.names = F,sep = "\t")
size_data$Length_Group <- factor(size_data$Length_Group, levels=unique(size_data$Length_Group))


defense_number <- size_data[,c(1,12)]
defense_number2 <- tapply(defense_number$Length_Group, defense_number$Length_Group, length) %>% as.data.frame() %>% rownames_to_column("TAG")
defense_number2 <- defense_number2 %>% dplyr::rename(defense_number=".")

plasmids_number <- size_data[,c(1,12)] %>% unique()
plasmids_number2 <- tapply(plasmids_number$Length_Group, plasmids_number$Length_Group, length) %>% as.data.frame() %>% rownames_to_column("TAG")
plasmids_number2 <- plasmids_number2 %>% dplyr::rename(plasmid_number=".")

new_number <- cbind(defense_number2,plasmids_number2)

new_number2 <- new_number[,c(1,2,4)]

# test_number <- new_number2 %>% dplyr::filter(new_number2$plasmid_number != "1")


new_number2$ratio <- round(new_number$defense_number/new_number$plasmid_number,2)
new_number2$TAG <- factor(new_number2$TAG, levels=unique(new_number2$TAG))

ggplot(new_number2,aes(x=TAG,y=ratio)) + 
  # geom_bar(fill="steelblue",stat = 'identity',width = 0.8) + 
  geom_text(aes(label=ratio),vjust = -0.2, hjust = 0.5,position = position_dodge2(width = 0.1, preserve = 'single')) + 
  # scale_x_continuous(breaks = c(0:13)) + 
  # scale_y_break(c(2050,29500),ticklabels = c(29500,30000),scales = 0.1) +
  labs(x="Size group", y="ratio(system number/plasmids number)") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 20, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.x = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        axis.title.y = element_text(size = 15, face = "bold", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.x = element_text(size = 10, face = "plain", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.y = element_text(size = 10, face = "bold", angle = 0, vjust = 0.5, hjust = 0.5),
        legend.title = element_text(size = 15, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.text = element_text(size = 12, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.key = element_rect(fill = 'transparent'),
        legend.position = 'bottom',
        legend.key.size=unit(0.8,'cm'),
        legend.key.width=unit(1.2,'cm'),
        legend.spacing.y = unit(0.5,"cm"),
        # plot.margin = unit(c(1, 1, 1, 1),'cm'),
        strip.text.y = element_text(size=15,face = "bold"),
        strip.text.x = element_text(size=15,face = "bold")
        )

if(do.write){
  ggsave(width=25,height=8,filename="../../Results/01.Distribution/size_1.pdf",limitsize = FALSE)
}







```


#