---
title: "System number - Gene map visualization"
author: "[Haotian Zheng](https://github.com/marveloushaotian)"
date: "`r Sys.Date()`"
output: html_document
---
**This document analysis:**  
*1.*  
*2.*  

***

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE) # Need to change the path of the plot.

library(knitr) # evaluate the code, putting the results in a markdown document, which can then be converted to a variety of formats with pandoc.
library(tidyverse) # including ggplot2,dplyr,tidyr,readr,purrr,tibble,stringr,forcats.
# Matrix processing
library(reshape2) # 'melt', 'cast' rebuild database.
library(plyr)
library(data.table)

# Statistic.
library(scales) # generic function whose default method centers and/or scales the columns of a numeric matrix.
library(psych)
library(vegan)
library(randomForest)
library(caret)

# Visualization.
library(igraph)
library(ggrepel) # repel overlapping text labels.
library(ggthemes) # contains extra themes, scales, and geoms, and functions for and related to ggplot2.
library(ggpubr) # facilitates the creation of beautiful ggplot2-based graphs.
library(gg.gap) # Easy to define segments in y-axis for 'ggplot2'.
library(ggbreak) # Effectively Utilize Plotting Space to Deal With Large Datasets and Outliers.
library(RColorBrewer)
library(pheatmap) # A function to draw clustered heatmaps.
library(gggenes) # provides a 'ggplot2' geom and helper functions for draw- ing gene arrow maps.
library(gggenomes)

do.write <- F
options(scipen = 200)
```

#### Import data.
```{r}
# combined_data <- read.delim("../Results/2.Combined_Data/final_combined2.txt",header = T, check.names = F)
defensefinder_padloc_combined_data <- read.delim("../../Results/00.Original_Data/04.combined_data/DefenseFinder_Padloc_Combine/Final_data.txt",header = T, check.names = F)
cctyper_data <- read.table("../../Results/00.Original_Data/03.cctyper_data/cctyper_combined_mar.txt",header = T,check.names = F)
metadata_plsdb <- read.delim("../../Results/00.Original_Data/00.meta_data/plsdb_metadata_mar.txt",header = T,sep = "\t")
cctyper_data2 <- left_join(cctyper_data[,c(-2)],metadata_plsdb)
cctyper_data3 <- cctyper_data2 %>% filter(cctyper_data2$Source != "CCTyper_Crispr")
combined_data <- rbind(defensefinder_padloc_combined_data,cctyper_data3)
# remove the stange plasmid.
combined_data2 <- combined_data %>% filter(combined_data$Plasmid_ID != "NZ_CP069303.1")
# write.table(combined_data2, "../Results/3.Preliminary_Analysis/all_combined_data.txt", sep = "\t", row.names = F)

argonaute_origin <- read.table("../../Results/00.Original_Data/10.argonaute_data/argonaute_origin_data.txt",header = T, check.names = F, sep = "\t")
argonaute_selected <- read.table("../../Results/00.Original_Data/10.argonaute_data/argonaute_selected_file.txt", header = T, check.names = F, sep = "\t")
combined_data2 <- read.table("../../Results/00.Original_Data/all_combined_data.txt", header = T, check.names = F, sep = "\t")

origin_metadata <- read_tsv("../../Results/00.Original_Data/00.meta_data/plsdb_filtered.tsv")
#---------------------

argonaute_origin <- read.table("../../Results/00.Original_Data/10.argonaute_data/argonaute_origin_data.txt",header = T, check.names = F, sep = "\t")
combined_data2 <- read.table("../../Results/00.Original_Data/all_combined_data.txt", header = T, check.names = F, sep = "\t")
argonaute_gggene <- read.table("../../Results/00.Original_Data/10.argonaute_data/argoplot.txt",header = T,check.names = F,sep = "\t")

arg_test <- read.table("../../Results/00.Original_Data/10.argonaute_data/argoplot_test.txt",header = T,check.names = F,sep = "\t")
exa_test <- read.table("../../Results/00.Original_Data/10.argonaute_data/example_test.txt",header = T,check.names = F,sep = "\t")
```

***

#### Filter data.
```{r}

```

***

#### Visualization.
```{r}

```

#### ggGenes with argonaute.
```{r}
ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene, label = gene)) + 
  geom_gene_arrow(arrowhead_height = unit(3, "mm"), arrowhead_width = unit(1, "mm")) + 
  geom_gene_label(align = "left") + 
  geom_blank(data = dummies) + 
  facet_wrap(~ molecule, scales = "free", ncol = 1) + 
  scale_fill_brewer(palette = "Set3") + 
  theme_genes()
```

```{r}
# get gggene data.
ar_data1 <- combined_data2 %>% filter(combined_data2$Plasmid_ID %in%  argonaute_selected$Plasmid_ID)
# ar_data1$Plasmid_ID <- as.factor(ar_data1$Plasmid_ID)
ar_data2 <- ar_data1[,c(1,2,4,5,8)]
ar_data2$Strand <- as.character(ar_data2$Strand)

# visualization.

# options(repr.plot.width = 20, repr.plot.height = 1000)
# dev.new(width=100, height=1000, unit="px")

ar_data2$System_Beg <- as.numeric(ar_data2$System_Beg)
ar_data2$System_End <- as.numeric(ar_data2$System_End)

dummies <- make_alignment_dummies(
  ar_data2,
  aes(xmin = System_Beg, xmax = System_End, y = Plasmid_ID, id = Defense_System_Type),
  on = "ARGONAUTE"
)

ar_data2 %>% 

# ar_data3 <- ar_data2 %>% filter(ar_data2$Plasmid_ID == "AP018320.1")

ggplot(ar_data3, aes(xmin = System_Beg, xmax = System_End, y = Plasmid_ID, fill = Defense_System_Type)) +
  geom_gene_arrow() +
  facet_wrap(~ Plasmid_ID, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3")

if(do.write){
  ggsave(width=6,height=1,filename="../Results/3.Preliminary_Analysis/test.pdf",limitsize = FALSE)
}


# ggplot(ar_data3, aes(xmin = System_Beg, xmax = System_End, y = Plasmid_ID, fill = Defense_System_Type)) + 
#   geom_gene_arrow() +
#   geom_blank(data = dummies) +
#   facet_wrap(~ Plasmid_ID, scales = "free", ncol = 1) +
#   scale_fill_brewer(palette = color_my41) +
#   theme_genes()
```

### Select argonaute data(also including the selected data.)
```{r}
dummies_ar <- make_alignment_dummies(
  argonaute_gggene[c(264:311),],
  aes(xmin = System_Beg, xmax = System_End, y = Plasmid_ID, id = Defense_System),
  on = "argonaute"
)

ggplot(argonaute_gggene[c(264:311),], aes(xmin = System_Beg, xmax = System_End, y = Plasmid_ID, fill = Defense_System)) +
  geom_gene_arrow() +
  geom_blank(data = dummies_ar) +
  facet_wrap(~ Plasmid_ID, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes()

if(do.write){
  ggsave(width=20,height=8,filename="../../Results/04.GeneMap/Argonaute_6.pdf",limitsize = FALSE)
}
```
```{r}
data(package="gggenomes")

gggenomes(argonaute_gggene, emale_seqs, emale_tirs, emale_ava) %>%
  add_feats(ngaros=emale_ngaros, gc=emale_gc) %>%
  add_sublinks(emale_prot_ava) %>%
  flip_by_links() +
  geom_feat(position="identity", size=6) +
  geom_seq() +
  geom_link(data=links(2)) +
  geom_bin_label() +
  geom_gene(aes(fill=name)) +
  geom_gene_tag(aes(label=name), nudge_y=0.1, check_overlap = TRUE) +
  geom_feat(data=feats(ngaros), alpha=.3, size=10, position="identity") +
  geom_feat_note(aes(label="Ngaro-transposon"), feats(ngaros),
      nudge_y=.1, vjust=0) +
  geom_ribbon(aes(x=(x+xend)/2, ymax=y+.24, ymin=y+.38-(.4*score),
      group=seq_id, linetype="GC-content"), feats(gc),
      fill="lavenderblush4", position=position_nudge(y=-.1)) +
  scale_fill_brewer("Genes", palette="Dark2", na.value="cornsilk3")
```


***

##### Fin.